name: pole_chudes
description: Игра «Поле чудес» на Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fortune_wheel: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/questions.json
    - assets/mystery_questions.json
